/* tslint:disable */
/* eslint-disable */
export const frb_dart_fn_deliver_output: (a: number, b: any, c: number, d: number) => void;
export const frb_get_rust_content_hash: () => number;
export const frb_pde_ffi_dispatcher_primary: (a: number, b: any, c: any, d: number, e: number) => void;
export const frb_pde_ffi_dispatcher_sync: (a: number, b: any, c: number, d: number) => any;
export const __wbg_workerpool_free: (a: number, b: number) => void;
export const workerpool_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number];
export const workerpool_new_raw: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number];
export const frb_dart_opaque_dart2rust_encode: (a: any, b: any) => number;
export const frb_dart_opaque_drop_thread_box_persistent_handle: (a: number) => void;
export const frb_dart_opaque_rust2dart_decode: (a: number) => any;
export const frb_rust_vec_u8_free: (a: number, b: number) => void;
export const frb_rust_vec_u8_new: (a: number) => number;
export const frb_rust_vec_u8_resize: (a: number, b: number, c: number) => number;
export const receive_transfer_closure: (a: number, b: number, c: number) => [number, number];
export const wasm_start_callback: () => void;
export const wasm_bindgen_45412df3e7992a42___convert__closures_____invoke___web_sys_cbdbd214522c8e58___features__gen_Event__Event______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_45412df3e7992a42___convert__closures_____invoke___web_sys_cbdbd214522c8e58___features__gen_MessageEvent__MessageEvent______true_: (a: number, b: number, c: any) => void;
export const memory: WebAssembly.Memory;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
