// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field, public_member_api_docs

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

import 'api/core/config/dicom_config.dart';
import 'api/core/models/dicom_frame_result.dart';
import 'api/core/models/dicom_metadata.dart';
import 'api/core/utils/process_dicom_file.dart';
import 'api/init.dart';
import 'frb_generated.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(final dynamic raw);

  @protected
  String dco_decode_String(final dynamic raw);

  @protected
  bool dco_decode_bool(final dynamic raw);

  @protected
  DicomConfig dco_decode_box_autoadd_dicom_config(final dynamic raw);

  @protected
  DicomFrameResult dco_decode_box_autoadd_dicom_frame_result(final dynamic raw);

  @protected
  DicomMetadata dco_decode_box_autoadd_dicom_metadata(final dynamic raw);

  @protected
  DicomConfig dco_decode_dicom_config(final dynamic raw);

  @protected
  DicomFrameResult dco_decode_dicom_frame_result(final dynamic raw);

  @protected
  DicomMetadata dco_decode_dicom_metadata(final dynamic raw);

  @protected
  double dco_decode_f_32(final dynamic raw);

  @protected
  int dco_decode_i_16(final dynamic raw);

  @protected
  Int16List dco_decode_list_prim_i_16_strict(final dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(final dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(final dynamic raw);

  @protected
  int dco_decode_u_16(final dynamic raw);

  @protected
  int dco_decode_u_32(final dynamic raw);

  @protected
  int dco_decode_u_8(final dynamic raw);

  @protected
  void dco_decode_unit(final dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(
      final SseDeserializer deserializer);

  @protected
  String sse_decode_String(final SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(final SseDeserializer deserializer);

  @protected
  DicomConfig sse_decode_box_autoadd_dicom_config(
      final SseDeserializer deserializer);

  @protected
  DicomFrameResult sse_decode_box_autoadd_dicom_frame_result(
      final SseDeserializer deserializer);

  @protected
  DicomMetadata sse_decode_box_autoadd_dicom_metadata(
      final SseDeserializer deserializer);

  @protected
  DicomConfig sse_decode_dicom_config(final SseDeserializer deserializer);

  @protected
  DicomFrameResult sse_decode_dicom_frame_result(
      final SseDeserializer deserializer);

  @protected
  DicomMetadata sse_decode_dicom_metadata(final SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(final SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(final SseDeserializer deserializer);

  @protected
  Int16List sse_decode_list_prim_i_16_strict(
      final SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(final SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(final SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(final SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(final SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(final SseDeserializer deserializer);

  @protected
  void sse_decode_unit(final SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(final SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      final AnyhowException self, final SseSerializer serializer);

  @protected
  void sse_encode_String(final String self, final SseSerializer serializer);

  @protected
  void sse_encode_bool(final bool self, final SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dicom_config(
      final DicomConfig self, final SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dicom_frame_result(
      final DicomFrameResult self, final SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dicom_metadata(
      final DicomMetadata self, final SseSerializer serializer);

  @protected
  void sse_encode_dicom_config(
      final DicomConfig self, final SseSerializer serializer);

  @protected
  void sse_encode_dicom_frame_result(
      final DicomFrameResult self, final SseSerializer serializer);

  @protected
  void sse_encode_dicom_metadata(
      final DicomMetadata self, final SseSerializer serializer);

  @protected
  void sse_encode_f_32(final double self, final SseSerializer serializer);

  @protected
  void sse_encode_i_16(final int self, final SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_16_strict(
      final Int16List self, final SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(
      final List<int> self, final SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      final Uint8List self, final SseSerializer serializer);

  @protected
  void sse_encode_u_16(final int self, final SseSerializer serializer);

  @protected
  void sse_encode_u_32(final int self, final SseSerializer serializer);

  @protected
  void sse_encode_u_8(final int self, final SseSerializer serializer);

  @protected
  void sse_encode_unit(final void self, final SseSerializer serializer);

  @protected
  void sse_encode_i_32(final int self, final SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(final ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
