// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'api/core/config/dicom_config.dart';
import 'api/core/models/dicom_frame_result.dart';
import 'api/core/models/dicom_metadata.dart';
import 'api/core/utils/process_dicom_file.dart';
import 'api/init.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  RustLib._();
  @internal
  static final instance = RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    final RustLibApi? api,
    final BaseHandler? handler,
    final ExternalLibrary? externalLibrary,
    final bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required final RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -451762164;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'dicom_toolkit',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<DicomConfig> crateApiCoreConfigDicomConfigDicomConfigDefault();

  Future<DicomFrameResult>
      crateApiCoreModelsDicomFrameResultDicomFrameResultNew(
          {required final DicomFrameResult result});

  Future<DicomMetadata> crateApiCoreModelsDicomMetadataDicomMetadataDefault();

  Future<DicomMetadata> crateApiCoreModelsDicomMetadataDicomMetadataNew(
      {required final DicomMetadata data});

  Future<void> crateApiInitInitApp();

  Future<DicomFrameResult> crateApiInitLoadDicom(
      {required final String path, required final DicomConfig config});

  Future<DicomFrameResult> crateApiInitLoadDicomFromBytes(
      {required final List<int> bytes, required final DicomConfig config});

  Future<DicomFrameResult> crateApiCoreUtilsProcessDicomFileProcessDicomFile(
      {required final String path, required final DicomConfig config});

  Future<DicomFrameResult>
      crateApiCoreUtilsProcessDicomFileProcessDicomFromBytes(
          {required final List<int> bytes, required final DicomConfig config});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<DicomConfig> crateApiCoreConfigDicomConfigDicomConfigDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (final port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dicom_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCoreConfigDicomConfigDicomConfigDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreConfigDicomConfigDicomConfigDefaultConstMeta =>
      const TaskConstMeta(
        debugName: 'dicom_config_default',
        argNames: [],
      );

  @override
  Future<DicomFrameResult>
      crateApiCoreModelsDicomFrameResultDicomFrameResultNew(
          {required final DicomFrameResult result}) {
    return handler.executeNormal(NormalTask(
      callFfi: (final port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_dicom_frame_result(result, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dicom_frame_result,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiCoreModelsDicomFrameResultDicomFrameResultNewConstMeta,
      argValues: [result],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiCoreModelsDicomFrameResultDicomFrameResultNewConstMeta =>
          const TaskConstMeta(
            debugName: 'dicom_frame_result_new',
            argNames: ['result'],
          );

  @override
  Future<DicomMetadata> crateApiCoreModelsDicomMetadataDicomMetadataDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (final port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dicom_metadata,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCoreModelsDicomMetadataDicomMetadataDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiCoreModelsDicomMetadataDicomMetadataDefaultConstMeta =>
          const TaskConstMeta(
            debugName: 'dicom_metadata_default',
            argNames: [],
          );

  @override
  Future<DicomMetadata> crateApiCoreModelsDicomMetadataDicomMetadataNew(
      {required final DicomMetadata data}) {
    return handler.executeNormal(NormalTask(
      callFfi: (final port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_dicom_metadata(data, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dicom_metadata,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCoreModelsDicomMetadataDicomMetadataNewConstMeta,
      argValues: [data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreModelsDicomMetadataDicomMetadataNewConstMeta =>
      const TaskConstMeta(
        debugName: 'dicom_metadata_new',
        argNames: ['data'],
      );

  @override
  Future<void> crateApiInitInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (final port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInitInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitInitAppConstMeta => const TaskConstMeta(
        debugName: 'init_app',
        argNames: [],
      );

  @override
  Future<DicomFrameResult> crateApiInitLoadDicom(
      {required final String path, required final DicomConfig config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (final port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_box_autoadd_dicom_config(config, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dicom_frame_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiInitLoadDicomConstMeta,
      argValues: [path, config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitLoadDicomConstMeta => const TaskConstMeta(
        debugName: 'load_dicom',
        argNames: ['path', 'config'],
      );

  @override
  Future<DicomFrameResult> crateApiInitLoadDicomFromBytes(
      {required final List<int> bytes, required final DicomConfig config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (final port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        sse_encode_box_autoadd_dicom_config(config, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dicom_frame_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiInitLoadDicomFromBytesConstMeta,
      argValues: [bytes, config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitLoadDicomFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: 'load_dicom_from_bytes',
        argNames: ['bytes', 'config'],
      );

  @override
  Future<DicomFrameResult> crateApiCoreUtilsProcessDicomFileProcessDicomFile(
      {required final String path, required final DicomConfig config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (final port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_box_autoadd_dicom_config(config, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dicom_frame_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreUtilsProcessDicomFileProcessDicomFileConstMeta,
      argValues: [path, config],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiCoreUtilsProcessDicomFileProcessDicomFileConstMeta =>
          const TaskConstMeta(
            debugName: 'process_dicom_file',
            argNames: ['path', 'config'],
          );

  @override
  Future<DicomFrameResult>
      crateApiCoreUtilsProcessDicomFileProcessDicomFromBytes(
          {required final List<int> bytes, required final DicomConfig config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (final port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        sse_encode_box_autoadd_dicom_config(config, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dicom_frame_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta:
          kCrateApiCoreUtilsProcessDicomFileProcessDicomFromBytesConstMeta,
      argValues: [bytes, config],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiCoreUtilsProcessDicomFileProcessDicomFromBytesConstMeta =>
          const TaskConstMeta(
            debugName: 'process_dicom_from_bytes',
            argNames: ['bytes', 'config'],
          );

  @protected
  AnyhowException dco_decode_AnyhowException(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DicomConfig dco_decode_box_autoadd_dicom_config(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dicom_config(raw);
  }

  @protected
  DicomFrameResult dco_decode_box_autoadd_dicom_frame_result(
      final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dicom_frame_result(raw);
  }

  @protected
  DicomMetadata dco_decode_box_autoadd_dicom_metadata(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dicom_metadata(raw);
  }

  @protected
  DicomConfig dco_decode_dicom_config(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DicomConfig(
      autoNormalize: dco_decode_bool(arr[0]),
      skipPixels: dco_decode_bool(arr[1]),
    );
  }

  @protected
  DicomFrameResult dco_decode_dicom_frame_result(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DicomFrameResult(
      metadata: dco_decode_dicom_metadata(arr[0]),
      pixelData: dco_decode_list_prim_i_16_strict(arr[1]),
    );
  }

  @protected
  DicomMetadata dco_decode_dicom_metadata(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 27)
      throw Exception('unexpected arr length: expect 27 but see ${arr.length}');
    return DicomMetadata(
      patientId: dco_decode_String(arr[0]),
      patientName: dco_decode_String(arr[1]),
      studyDate: dco_decode_String(arr[2]),
      studyDescription: dco_decode_String(arr[3]),
      modality: dco_decode_String(arr[4]),
      manufacturer: dco_decode_String(arr[5]),
      manufacturerModelName: dco_decode_String(arr[6]),
      institutionName: dco_decode_String(arr[7]),
      studyInstanceUid: dco_decode_String(arr[8]),
      seriesInstanceUid: dco_decode_String(arr[9]),
      sopInstanceUid: dco_decode_String(arr[10]),
      seriesDescription: dco_decode_String(arr[11]),
      bodyPartExamined: dco_decode_String(arr[12]),
      sliceThickness: dco_decode_f_32(arr[13]),
      instanceNumber: dco_decode_String(arr[14]),
      photometricInterpretation: dco_decode_String(arr[15]),
      width: dco_decode_u_32(arr[16]),
      height: dco_decode_u_32(arr[17]),
      windowCenter: dco_decode_f_32(arr[18]),
      windowWidth: dco_decode_f_32(arr[19]),
      rescaleIntercept: dco_decode_f_32(arr[20]),
      rescaleSlope: dco_decode_f_32(arr[21]),
      samplesPerPixel: dco_decode_u_16(arr[22]),
      bitsAllocated: dco_decode_u_16(arr[23]),
      bitsStored: dco_decode_u_16(arr[24]),
      highBit: dco_decode_u_16(arr[25]),
      pixelRepresentation: dco_decode_u_16(arr[26]),
    );
  }

  @protected
  double dco_decode_f_32(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_16(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Int16List dco_decode_list_prim_i_16_strict(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int16List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_16(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(final dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(
      final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DicomConfig sse_decode_box_autoadd_dicom_config(
      final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dicom_config(deserializer));
  }

  @protected
  DicomFrameResult sse_decode_box_autoadd_dicom_frame_result(
      final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dicom_frame_result(deserializer));
  }

  @protected
  DicomMetadata sse_decode_box_autoadd_dicom_metadata(
      final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dicom_metadata(deserializer));
  }

  @protected
  DicomConfig sse_decode_dicom_config(final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_autoNormalize = sse_decode_bool(deserializer);
    final var_skipPixels = sse_decode_bool(deserializer);
    return DicomConfig(
        autoNormalize: var_autoNormalize, skipPixels: var_skipPixels);
  }

  @protected
  DicomFrameResult sse_decode_dicom_frame_result(
      final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_metadata = sse_decode_dicom_metadata(deserializer);
    final var_pixelData = sse_decode_list_prim_i_16_strict(deserializer);
    return DicomFrameResult(metadata: var_metadata, pixelData: var_pixelData);
  }

  @protected
  DicomMetadata sse_decode_dicom_metadata(final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_patientId = sse_decode_String(deserializer);
    final var_patientName = sse_decode_String(deserializer);
    final var_studyDate = sse_decode_String(deserializer);
    final var_studyDescription = sse_decode_String(deserializer);
    final var_modality = sse_decode_String(deserializer);
    final var_manufacturer = sse_decode_String(deserializer);
    final var_manufacturerModelName = sse_decode_String(deserializer);
    final var_institutionName = sse_decode_String(deserializer);
    final var_studyInstanceUid = sse_decode_String(deserializer);
    final var_seriesInstanceUid = sse_decode_String(deserializer);
    final var_sopInstanceUid = sse_decode_String(deserializer);
    final var_seriesDescription = sse_decode_String(deserializer);
    final var_bodyPartExamined = sse_decode_String(deserializer);
    final var_sliceThickness = sse_decode_f_32(deserializer);
    final var_instanceNumber = sse_decode_String(deserializer);
    final var_photometricInterpretation = sse_decode_String(deserializer);
    final var_width = sse_decode_u_32(deserializer);
    final var_height = sse_decode_u_32(deserializer);
    final var_windowCenter = sse_decode_f_32(deserializer);
    final var_windowWidth = sse_decode_f_32(deserializer);
    final var_rescaleIntercept = sse_decode_f_32(deserializer);
    final var_rescaleSlope = sse_decode_f_32(deserializer);
    final var_samplesPerPixel = sse_decode_u_16(deserializer);
    final var_bitsAllocated = sse_decode_u_16(deserializer);
    final var_bitsStored = sse_decode_u_16(deserializer);
    final var_highBit = sse_decode_u_16(deserializer);
    final var_pixelRepresentation = sse_decode_u_16(deserializer);
    return DicomMetadata(
        patientId: var_patientId,
        patientName: var_patientName,
        studyDate: var_studyDate,
        studyDescription: var_studyDescription,
        modality: var_modality,
        manufacturer: var_manufacturer,
        manufacturerModelName: var_manufacturerModelName,
        institutionName: var_institutionName,
        studyInstanceUid: var_studyInstanceUid,
        seriesInstanceUid: var_seriesInstanceUid,
        sopInstanceUid: var_sopInstanceUid,
        seriesDescription: var_seriesDescription,
        bodyPartExamined: var_bodyPartExamined,
        sliceThickness: var_sliceThickness,
        instanceNumber: var_instanceNumber,
        photometricInterpretation: var_photometricInterpretation,
        width: var_width,
        height: var_height,
        windowCenter: var_windowCenter,
        windowWidth: var_windowWidth,
        rescaleIntercept: var_rescaleIntercept,
        rescaleSlope: var_rescaleSlope,
        samplesPerPixel: var_samplesPerPixel,
        bitsAllocated: var_bitsAllocated,
        bitsStored: var_bitsStored,
        highBit: var_highBit,
        pixelRepresentation: var_pixelRepresentation);
  }

  @protected
  double sse_decode_f_32(final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_16(final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt16();
  }

  @protected
  Int16List sse_decode_list_prim_i_16_strict(
      final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt16List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(
      final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_16(final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(final SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      final AnyhowException self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(final String self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(final bool self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_dicom_config(
      final DicomConfig self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dicom_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_dicom_frame_result(
      final DicomFrameResult self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dicom_frame_result(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_dicom_metadata(
      final DicomMetadata self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dicom_metadata(self, serializer);
  }

  @protected
  void sse_encode_dicom_config(
      final DicomConfig self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.autoNormalize, serializer);
    sse_encode_bool(self.skipPixels, serializer);
  }

  @protected
  void sse_encode_dicom_frame_result(
      final DicomFrameResult self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dicom_metadata(self.metadata, serializer);
    sse_encode_list_prim_i_16_strict(self.pixelData, serializer);
  }

  @protected
  void sse_encode_dicom_metadata(
      final DicomMetadata self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.patientId, serializer);
    sse_encode_String(self.patientName, serializer);
    sse_encode_String(self.studyDate, serializer);
    sse_encode_String(self.studyDescription, serializer);
    sse_encode_String(self.modality, serializer);
    sse_encode_String(self.manufacturer, serializer);
    sse_encode_String(self.manufacturerModelName, serializer);
    sse_encode_String(self.institutionName, serializer);
    sse_encode_String(self.studyInstanceUid, serializer);
    sse_encode_String(self.seriesInstanceUid, serializer);
    sse_encode_String(self.sopInstanceUid, serializer);
    sse_encode_String(self.seriesDescription, serializer);
    sse_encode_String(self.bodyPartExamined, serializer);
    sse_encode_f_32(self.sliceThickness, serializer);
    sse_encode_String(self.instanceNumber, serializer);
    sse_encode_String(self.photometricInterpretation, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_f_32(self.windowCenter, serializer);
    sse_encode_f_32(self.windowWidth, serializer);
    sse_encode_f_32(self.rescaleIntercept, serializer);
    sse_encode_f_32(self.rescaleSlope, serializer);
    sse_encode_u_16(self.samplesPerPixel, serializer);
    sse_encode_u_16(self.bitsAllocated, serializer);
    sse_encode_u_16(self.bitsStored, serializer);
    sse_encode_u_16(self.highBit, serializer);
    sse_encode_u_16(self.pixelRepresentation, serializer);
  }

  @protected
  void sse_encode_f_32(final double self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_16(final int self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt16(self);
  }

  @protected
  void sse_encode_list_prim_i_16_strict(
      final Int16List self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt16List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      final List<int> self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      final Uint8List self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_16(final int self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(final int self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(final int self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(final void self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(final int self, final SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
