// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../../frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Configuration options for the DICOM processing engine.
///
/// Use this struct to tune the balance between precision and performance.
class DicomConfig {
  const DicomConfig({
    required this.autoNormalize,
    required this.skipPixels,
  });

  /// If true, the pixel values will be automatically normalized into standard ranges
  /// based on the metadata found in the DICOM headers.
  final bool autoNormalize;

  /// If true, the Rust engine will only parse the file metadata (tags) and
  /// skip the expensive pixel data extraction. This is useful for building
  /// fast metadata viewers or file explorers.
  final bool skipPixels;

  /// Provides the standard production-ready defaults:
  /// - auto_normalize: true
  /// - skip_pixels: false
  static Future<DicomConfig> default_() =>
      RustLib.instance.api.crateApiCoreConfigDicomConfigDicomConfigDefault();

  @override
  int get hashCode => autoNormalize.hashCode ^ skipPixels.hashCode;

  @override
  bool operator ==(final Object other) =>
      identical(this, other) ||
      other is DicomConfig &&
          runtimeType == other.runtimeType &&
          autoNormalize == other.autoNormalize &&
          skipPixels == other.skipPixels;
}
