// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../../frb_generated.dart';
import '../config/dicom_config.dart';
import '../models/dicom_frame_result.dart';
import '../models/dicom_metadata.dart';

// These functions are ignored because they are not marked as `pub`: `get_float_tag`, `get_int_tag`, `get_str_tag`, `process_dicom_object`

/// Internal utility function for parsing a DICOM file and extracting its metadata and pixels.
///
/// This function uses the `dicom-rs` ecosystem to handle the complex structure of DICOM objects.
///
/// # Implementation Details:
/// - **Metadata Extraction**: Uses clean helper functions to extract all critical tags with
///   sensible fallback defaults for missing or malformed headers.
/// - **Resilience**: Provides sane defaults for missing tags often encountered in non-standard DICOM files.
/// - **Pixel Extraction**: Attempts direct byte-chunking first (fast path for uncompressed data),
///   falling back to the `dicom` crate's transfer-syntax-aware decoding for compressed formats.
///
/// # Returns
/// - `Ok(DicomFrameResult)` on successful processing.
/// - `Err` if the file could not be opened or is missing critical metadata.
Future<DicomFrameResult> processDicomFile(
        {required final String path, required final DicomConfig config}) =>
    RustLib.instance.api.crateApiCoreUtilsProcessDicomFileProcessDicomFile(
        path: path, config: config);

Future<DicomFrameResult> processDicomFromBytes(
        {required final List<int> bytes, required final DicomConfig config}) =>
    RustLib.instance.api.crateApiCoreUtilsProcessDicomFileProcessDicomFromBytes(
        bytes: bytes, config: config);
