// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../../frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Represents the extracted medical metadata from a DICOM file header.
///
/// This struct contains critical parameters for clinical rendering,
/// including spatial dimensions, windowing defaults, and patient identity.
class DicomMetadata {
  const DicomMetadata({
    required this.patientId,
    required this.patientName,
    required this.studyDate,
    required this.studyDescription,
    required this.modality,
    required this.manufacturer,
    required this.manufacturerModelName,
    required this.institutionName,
    required this.studyInstanceUid,
    required this.seriesInstanceUid,
    required this.sopInstanceUid,
    required this.seriesDescription,
    required this.bodyPartExamined,
    required this.sliceThickness,
    required this.instanceNumber,
    required this.photometricInterpretation,
    required this.width,
    required this.height,
    required this.windowCenter,
    required this.windowWidth,
    required this.rescaleIntercept,
    required this.rescaleSlope,
    required this.samplesPerPixel,
    required this.bitsAllocated,
    required this.bitsStored,
    required this.highBit,
    required this.pixelRepresentation,
  });

  /// The hospital-assigned patient identifier (e.g., MRN). Tag (0010,0020).
  final String patientId;

  /// The name of the patient as recorded in the file header. Tag (0010,0010).
  final String patientName;

  /// The date the study was performed, in DICOM format (YYYYMMDD). Tag (0008,0020).
  final String studyDate;

  /// A description of the study (e.g., "R/O pneumonia"). Tag (0008,1030).
  final String studyDescription;

  /// The imaging modality (e.g., "CT", "MR", "US", "XA"). Tag (0008,0060).
  final String modality;

  /// The manufacturer of the imaging device (e.g., "SIEMENS"). Tag (0008,0070).
  final String manufacturer;

  /// The manufacturer's model name (e.g., "SOMATOM Force"). Tag (0008,1090).
  final String manufacturerModelName;

  /// The institution where the study was performed. Tag (0008,0080).
  final String institutionName;

  /// Globally unique identifier for the study. Tag (0020,000D).
  final String studyInstanceUid;

  /// Globally unique identifier for the series within the study. Tag (0020,000E).
  final String seriesInstanceUid;

  /// Globally unique identifier for this specific SOP Instance. Tag (0008,0018).
  final String sopInstanceUid;

  /// A description of the series (e.g., "Axial T2 FLAIR"). Tag (0008,103E).
  final String seriesDescription;

  /// The body part examined (e.g., "CHEST", "ABDOMEN"). Tag (0018,0015).
  final String bodyPartExamined;

  /// The slice thickness in mm. Tag (0018,0050).
  final double sliceThickness;

  /// The instance (frame) number within the series. Tag (0020,0013).
  final String instanceNumber;

  /// The Photometric Interpretation (e.g., "MONOCHROME1", "MONOCHROME2").
  /// Informs the renderer how to map pixel values to grayscale intensities.
  final String photometricInterpretation;

  /// The number of pixel columns in the image.
  final int width;

  /// The number of pixel rows in the image.
  final int height;

  /// The default Window Center (Level) provided in the DICOM metadata.
  final double windowCenter;

  /// The default Window Width provided in the DICOM metadata.
  final double windowWidth;

  /// The Rescale Intercept (Tag 0028,1052).
  final double rescaleIntercept;

  /// The Rescale Slope (Tag 0028,1053).
  final double rescaleSlope;

  /// The number of color components in this image (e.g., 1 for Grayscale).
  final int samplesPerPixel;

  /// The number of bits allocated per pixel (typically 16).
  final int bitsAllocated;

  /// The number of bits actually used to store the pixel data (typically 12 or 16).
  final int bitsStored;

  /// The most significant bit of the pixel data (typically bits_stored - 1).
  final int highBit;

  /// Specifies whether the pixel data is signed (1) or unsigned (0).
  final int pixelRepresentation;

  /// Provides sensible default values for DICOM metadata.
  /// These defaults are used when specific tags are missing from the file header.
  static Future<DicomMetadata> default_() => RustLib.instance.api
      .crateApiCoreModelsDicomMetadataDicomMetadataDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Creates a new [DicomMetadata] instance by copying values from another.
  /// Useful for ensuring a clean ownership transfer when constructing results.
  static Future<DicomMetadata> newInstance(
          {required final DicomMetadata data}) =>
      RustLib.instance.api
          .crateApiCoreModelsDicomMetadataDicomMetadataNew(data: data);

  @override
  int get hashCode =>
      patientId.hashCode ^
      patientName.hashCode ^
      studyDate.hashCode ^
      studyDescription.hashCode ^
      modality.hashCode ^
      manufacturer.hashCode ^
      manufacturerModelName.hashCode ^
      institutionName.hashCode ^
      studyInstanceUid.hashCode ^
      seriesInstanceUid.hashCode ^
      sopInstanceUid.hashCode ^
      seriesDescription.hashCode ^
      bodyPartExamined.hashCode ^
      sliceThickness.hashCode ^
      instanceNumber.hashCode ^
      photometricInterpretation.hashCode ^
      width.hashCode ^
      height.hashCode ^
      windowCenter.hashCode ^
      windowWidth.hashCode ^
      rescaleIntercept.hashCode ^
      rescaleSlope.hashCode ^
      samplesPerPixel.hashCode ^
      bitsAllocated.hashCode ^
      bitsStored.hashCode ^
      highBit.hashCode ^
      pixelRepresentation.hashCode;

  @override
  bool operator ==(final Object other) =>
      identical(this, other) ||
      other is DicomMetadata &&
          runtimeType == other.runtimeType &&
          patientId == other.patientId &&
          patientName == other.patientName &&
          studyDate == other.studyDate &&
          studyDescription == other.studyDescription &&
          modality == other.modality &&
          manufacturer == other.manufacturer &&
          manufacturerModelName == other.manufacturerModelName &&
          institutionName == other.institutionName &&
          studyInstanceUid == other.studyInstanceUid &&
          seriesInstanceUid == other.seriesInstanceUid &&
          sopInstanceUid == other.sopInstanceUid &&
          seriesDescription == other.seriesDescription &&
          bodyPartExamined == other.bodyPartExamined &&
          sliceThickness == other.sliceThickness &&
          instanceNumber == other.instanceNumber &&
          photometricInterpretation == other.photometricInterpretation &&
          width == other.width &&
          height == other.height &&
          windowCenter == other.windowCenter &&
          windowWidth == other.windowWidth &&
          rescaleIntercept == other.rescaleIntercept &&
          rescaleSlope == other.rescaleSlope &&
          samplesPerPixel == other.samplesPerPixel &&
          bitsAllocated == other.bitsAllocated &&
          bitsStored == other.bitsStored &&
          highBit == other.highBit &&
          pixelRepresentation == other.pixelRepresentation;
}
